README.md
classes/activity.php
classes/factories/activities_factory.php
classes/factories/learners_factory.php
classes/factories/trainings_factory.php
classes/forms/category_training_update_form.php
classes/forms/training_milestones_update_form.php
classes/gabarit/listtemplate.php
classes/generated/ajaxsrvmethod.php
classes/generated/createdpdf.php
classes/generated/preparedinf.php
classes/output/renderable/learner_details.php
classes/output/renderable/training_learners_list.php
classes/output/renderable/training_management.php
classes/output/renderable/training_milestones.php
classes/output/renderable/trainings_list.php
classes/output/renderer.php
classes/utils/db_accessor.php
db/access.php
db/install.xml
index.php
lang/en/tool_attestoodle.php
lang/fr/tool_attestoodle.php
lib.php
settings.php

mise en place de la pagination, optimisation du code et ajout du mode de consultation.
Les liens attestoosle sont désormais accessible directement au niveau du profil des utilisateurs.
Les liens au niveau de l'administration du site, nécessitent des droits étendus que les utilisateur gestionnaires n'ont pas à avoir

After submit

---

classes/factories/activities_factory.php
classes/forms/learner_certificate_form.php
classes/output/renderable/training_management.php
classes/privacy/provider.php
classes/utils/db_accessor.php
version.php

Prise en compte de l'API Privacy (RGPD)

Feature 73

---

classes/privacy/provider.php
classes/utils/db_accessor.php
version.php

prise en compte de la table tool_attestoodle_learner lors des suppressions

correction bug issue #82

---

classes/utils/db_accessor.php
version.php

correction selected (sans selection par défaut), lors de l'ajout des apprenants à une formation

Issue #86 bugfix

---

classes/output/renderable/training_management.php
classes/utils/plugins_accessor.php
lib.php
version.php

Liens vers plugins ext

---

classes/certificate.php
version.php

correction  issue #63

---

README.md
classes/forms/training_milestones_update_form.php
classes/gabarit/listtemplate.php
classes/gabarit/sitecertificate.php
classes/training/select_learners.php
classes/utils/plugins_accessor.php
index.php
version.php

Mise page url au format relatif

Correction issue #58

---

classes/gabarit/listtemplate.php
classes/output/renderable/training_management.php
classes/training/delete_training.php
lang/en/tool_attestoodle.php
lang/fr/tool_attestoodle.php
version.php

Ajout demande de confirmation lors de la suppression d'une formation issue #98

ajout confirmation suppr formation

---

.travis.yml
classes/output/renderable/learner_details.php
index.php
version.php

Optimisation de la génération d'attestation d'un apprenant

Optimisation 01

---

classes/forms/category_training_update_form.php
classes/output/renderable/training_management.php
version.php

Interdit 2 formations avec nom identique

Rule training name

---

classes/output/renderable/training_management.php
version.php

retrait de l'accès à la sauvegarde tant que la formation n'est pas validée

Bugfix save

---

classes/forms/category_training_update_form.php
lang/en/tool_attestoodle.php
lang/fr/tool_attestoodle.php
version.php

impose date de fin de formation supérieur à date de début

Rule training date

---

classes/utils/db_accessor.php
version.php

élargie la sélection des jalons en erreur en leur ajoutant ceux dont le cours est supprimé

Fixbug coursedelete

---

README.md
classes/factories/trainings_factory.php
classes/forms/category_training_update_form.php
classes/output/renderable/trainings_list.php
classes/output/renderer.php
classes/training.php
classes/training/delete_training.php
classes/utils/db_accessor.php
classes/utils/plugins_accessor.php
index.php
lang/en/tool_attestoodle.php
lang/fr/tool_attestoodle.php
version.php

correction mineur pour Moodle 3.8 et ajout support pour le plugin de planification des taches Attestooodle

Feature moodle 3 8

---

index.php
version.php

conservation de la date saisie lors du passage du rapport global à la page détail d'un apprenant

Bugfix trsfchoicedate

---

classes/output/renderable/trainings_list.php
lang/en/tool_attestoodle.php
lang/fr/tool_attestoodle.php
version.php

deadline corrected at the end of the course

Fixbug endtraining

---

README.md
classes/certificate.php
version.php

correction de la borne de fin pour le calcul des temps crédités

Issue 135 bugfix

---

db/install.xml
db/upgrade.php
version.php

correction définition schéma BDD (cf issue #137)

Bugfix 137

---

classes/utils/plugins_accessor.php
version.php

Bugfix 141

---

.travis.yml
classes/gabarit/view_export.php
classes/generated/createdpdf.php
classes/generated/preparedinf.php
classes/training/course_outof_categ.php
styles.css
version.php

Compatible with windows servers and corrects the css styles of the buttons

Ensures compatibility with Moodle 3.11

---

.github/workflows/moodle-ci.yml
classes/gabarit/sitecertificate.php
styles.css
version.php

Je n'ai pas trouvé l'utilité mais si vous savez, je ferai un meilleur selecteur pour ne pas que ça rentre en conflit avec le CSS de moodle
(penser à créer des classes spécifiques "attestoodle")
problème :

Conflit avec le CSS de moodle (boutton)

---

classes/forms/training_milestones_update_form.php
version.php

Issue 171 bug
